### ISSUE TITLE
Issues with chocolatey provider

### ISSUE THREAD

**Issue by leandrosolagna** [TheKevJames/puppet-homebrew#41]
In our environment, we use the chocolatey's module and when I installed the homebrew module, both modules started having problems with their providers. Could you, please, check how to separate the providers?

Thank you for your attention.

**Comment by TheKevJames** [comment]
Hey, could you give me a bit more information about this? I've never played with chocolatey, but AFAIK it's a windows-specific package manager. Since homebrew is OSX-specific, I'm at a loss as to how any node could run both modules.

Assuming you have some puppet config managing both OSX and Windows repos, make sure the packages configured to be installed on each have the correct provider set (ie. for Windows nodes each `package` target should have `provider => chocolatey` and for OSX nodes `provider => homebrew` (or brew, or brewcask)).

If you've done the above and you still have problems, please attach more information. Specifically:
- puppet-chocolately version
- puppet-homebrew version
- puppet version
- operating system version(s)
- log output showing the error

**Comment by jordigg** [comment]
We use Chocolatey and Brew on our environment and we don't have any issues. If you detail your code where you include both packages we can check it out.

We just apply the provider necessary for each platform applying classes specific for each OS. For example:

```
class profiles::common {
  
  case $::osfamily {
    #Debian/Ubuntu
    'Debian': {
      include profiles::common::debian
      if $::type == 'desktop' {
        include profiles::common::debian::gui
      }
    }
    #Mac OS X
    'Darwin': {
      include profiles::common::darwin
      if $::type == 'desktop' {
        include profiles::common::darwin::gui
      }
    }
    # Windows
    'Windows': {
      include profiles::common::windows
      if $::type == 'desktop' {
        include profiles::common::windows::gui
      }
    }
    # Default case
    default: {}
  }

}
```

**Comment by TheKevJames** [comment]
Closed as inactive. If @leandrosolagna wants to reopen by providing the requested information, feel free!
