### ISSUE TITLE
Print both "brew" and "brew cask" errors when "homebrew" provider fails

### ISSUE THREAD

**Issue by zbentley** [TheKevJames/puppet-homebrew#61]
Sometimes, packages installed with the `homebrew` provider fail to install. If the packages are real homebrew packages (not casks), the `homebrew` provider masks the actual installation error.

If the brew-to-cask fallback is used for a `homebrew`-provided package, the error output from the first `brew` command should be kept around. If the `brew cask` command also fails, both errors should be outputted. Even if both errors are "package not found", this is still useful info for users.

Special cases could be added for the STDERR/exit codes that indicate "package not found" if you wanted to reduce error volume, but I think printing both is probably a good start.

**Comment by jordigg** [comment]
This should be easy to implement. If @TheKevJames agrees I'll look into it.
Right now we only show the last error that happens together with a "package not found message".

**Comment by zbentley** [comment]
A possible way to detect if fallback is even necessary would be to parse the `brew install` output. If a package isn't available via core brew, but is available via a cask, the `brew search` results for it will only return `Caskroom`-prefixed things (I think; there may be a way to make `brew cask` taps that don't start with `Caskroom`, but if there is I've never seen it).

For example: `brew search google-chrome | grep -v Caskroom` exits with status 1, but `brew search gcc | grep -v Caskroom` exits with status 0.

Something like that could be used to determine if fallback was even necessary at all, provided that the cask detection was flexible enough to cope with user-specified taps.

Just a random idea.

**Comment by jordigg** [comment]
This is already the functionality. https://github.com/TheKevJames/puppet-homebrew/blob/master/lib/puppet/provider/package/homebrew.rb#L12

We check if package is available on brew (even before we try to install it), if fails we check on cask, if fails we report package not found and trow error, usually we show the output of the latest but we could show both but I guess the message is the same, package is available on brew/cask.

**Comment by TheKevJames** [comment]
Two things I'm getting from this issue:
- Theoretically, we could parse the output of `brew info :name` to determine whether we should even do the fallback. I'm torn on this one, since it could make the provider faster but would involve going back to parsing command output.
- Printing the error from `brew info :name` when the package fails to install from any source may have value. This is probably true, would be nice to forward any message we get from brew to the user. The issue here is with the `failonfail` stuff we've been playing with; I'm not sure we can get the message without breaking the fallback code.

**Comment by TheKevJames** [comment]
Actually, I'm not sure we can get output from `brew info :name` _at all_. Currently, we do not use `failonfail` [here](https://github.com/TheKevJames/puppet-homebrew/blob/master/lib/puppet/provider/package/homebrew.rb#L13) and an "error" (ie. that `brew info :name` failed and we should fallback to brewcask is identified by having nil output.

The only error output we can grab is from setting `failonfail`... on closer inspection of the code for this, though, it looks like the error message within the `ExecutionFailure` is just the [output that we already have](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/util/execution.rb#L86), ie the output that is nil in this case.

**Comment by jordigg** [comment]
On the first point, this is the actual behaviour. Before we install a package we run a `brew info` to check whether exists or not.
If doesn't exist on brew we check on brew cask. If any of them succeed then we do `brew install`.
https://github.com/TheKevJames/puppet-homebrew/blob/master/lib/puppet/provider/package/homebrew.rb#L12
On the second point we would need to go back to the "old" way and get `stdout` and `stderr` and pass it to the user. I can take a look into that but the important part is to know if package is available or not.

**Comment by TheKevJames** [comment]
1:
> If doesn't exist on brew we check on brew cask
Right, the idea is we could parse output to see it doesn't exist on brew and _there's no need to check brewcask_. I don't have a Mac available until Monday, but if I remember correctly: when `brew info x` fails, it does a search on `x` in both brew and brewcask, and returns matching packages. We could search that output for `Caskroom/x` -- if missing, don't fallback to brewcask.

I'm not liking that this would require output parsing, though, this sounds very easy to mis-parse.

2:
Yeah, I think rather than providing the actual error, we could just make out own. Since we know the error is something along the lines of "could not find package foo in brew sources", we could just output that. I wonder: if people are using the fallback provider, how much do they care which (brew vs brewcask) provider the package comes from?

**Comment by jordigg** [comment]
`brew info` just search on brew, `brew cask info` just on brew cask.

The one that looks into all taps is `brew search`. We could use `search` to check if it's present in one command but search requires parsing and is confusing since it shows you packages that contain the string on their names but may not be the one you are looking for.

**Comment by TheKevJames** [comment]
Ah, my bad, for some reason I thought `brew info` ran a `brew search` on failure.

**Comment by jordigg** [comment]
It just returns `no available formula with name "bla"`.
`brew list` check if package is installed using brew, for brew cask you require to run `brew cask list`
`brew info` checks only on brew taps but not on cask. cask packages require `brew cask info`
`brew search` does a search on all taps (including cask) and shows any package that contains the name of the package you are looking for.

**Comment by TheKevJames** [comment]
Cool. In that case, I'm not sure there's much we can/should do about this issue.

**Comment by TheKevJames** [comment]
Closing since we already do as much as possible here, as far as we know.
