### ISSUE TITLE
Error: Failed to apply catalog: No command brew defined for provider brew

### ISSUE THREAD

**Issue by jordigg** [TheKevJames/puppet-homebrew#72]
I continue having the following error intermittently on new systems:
`Error: Failed to apply catalog: No command brew defined for provider brew`

I'm not sure what is causing this error to appear on some new system and not on some others. I can confirm that if `brew` is already present before puppet runs the problem will disappear. May be related to the random order that puppet runs every time is executed.

The only way I've found to fix this issue is adding the following line
`commands :brew => '/usr/local/bin/brew'` 
into https://github.com/TheKevJames/puppet-homebrew/blob/master/lib/puppet/provider/package/brew.rb

This shouldn't interfere with anything else, so I would suggest adding it in order to get rid of this random errors. What do you say @TheKevJames?

**Comment by TheKevJames** [comment]
Hmm, that line is already present in https://github.com/TheKevJames/puppet-homebrew/blob/master/lib/puppet/provider/package/brewcommon.rb#L15 . I wonder if this means the `commands` and `has_features` blocks are all uninheritable? Maybe we should move all of those into all three of the providers, instead of the base class?

Somewhat related: I'm very leery of merging anything new until I figure out why CI is failing. See https://github.com/TheKevJames/puppet-homebrew/pull/71 for the most up-to-date branch dealing with that... any ideas would be appreciated.

**Comment by jordigg** [comment]
Will have a look into CI. Is strange, was checking some of the errors and for example:
`brew info ack` reports as not found and then `brew cask info ack` fails which is correct.
Happens as well with `brew info git` and `brew cask info google-chrome` and when tested on a real machine seems to work just fine...
Not sure why on some tests works and on others does not.

**Comment by jordigg** [comment]
Since adding that change I haven't had any issues so far with nay new system. Not sure right now on the implications but I would suggest adding `commands :brew => '/usr/local/bin/brew'` to each provider and removing it from it's parent.
Will try with that and report.
