### ISSUE TITLE
Ability to add or remove taps

### ISSUE THREAD

**Issue by jordigg** [TheKevJames/puppet-homebrew#8]
Would be interesting to add the ability to manage Taps via puppet. [This module](https://forge.puppetlabs.com/gildas/homebrew) does it, would it be difficult to implement?

**Comment by jordigg** [comment]
Added the functionality [here](https://github.com/improbable-io/puppet-homebrew/tree/tapmanager) the same way they did on the other module. If you want to add it maybe it should be mentioned on the file or the copyright?

The Readme have been updated too.

**Comment by TheKevJames** [comment]
That would be awesome! I'd love to add this feature -- PRs are always appreciated, otherwise I'll put it on my TODO list. I have been pretty busy lately, (and focusing most of my off time on [a puppet testing module](https://github.com/TheKevJames/puppettools/tree/master/moduletest), which should help with some of the issues I've been seeing), but I should be able to get around to it eventually.

**Comment by TheKevJames** [comment]
Huh, just checked, would ya believe I had [this file](https://github.com/gildas/puppet-homebrew/blob/master/lib/puppet/provider/package/tap.rb) in my bookmarks as a TODO? :P
